awsApp:
  region: 'us-east-1'
  UserPoolId: 'us-east-1_je079j53O'
  IdentityPoolId: 'us-east-1:5b7119a4-6871-4c87-9387-8b06030c2b01'
  ClientId: '647kgohecrr5c4b7q3j4snarc6'
  Provider: 'cognito-idp.us-east-1.amazonaws.com/us-east-1_je079j53O'
